In [1]:
#numpy 참고 사이트: https://numpy.org/

In [4]:
import numpy as np  #shift+enter
names=np.array(['Bob','Joe','Will','Bob','Joe','Will'])



array([ True, False, False,  True, False, False])

In [ ]:
names=='Bob'

In [7]:
data=np.random.randn(6,4)
data

array([[-0.77422036,  0.65101708, -0.036529  ,  2.43213425],
       [ 0.03553746, -0.16168727, -1.42781337,  0.24927037],
       [ 0.34969587, -0.50383691,  1.09878003,  1.27534775],
       [ 0.56334927, -1.39183603,  1.01078987,  0.09362136],
       [-0.68733568,  0.23643794, -0.44920837, -0.28485182],
       [ 1.39218785,  0.30143936, -2.40804762, -1.65668287]])

In [8]:
data[names=='Bob'] #'Bob'에 해당하는 (TRUE) 데이터 행 추출

array([[-0.77422036,  0.65101708, -0.036529  ,  2.43213425],
       [ 0.56334927, -1.39183603,  1.01078987,  0.09362136]])

In [9]:
names[names=='Bob']

array(['Bob', 'Bob'], dtype='<U4')

In [10]:
names=='Bob'

array([ True, False, False,  True, False, False])

In [13]:
data[names=='Bob', 2:]  



array([[-0.036529  ,  2.43213425],
       [ 1.01078987,  0.09362136]])

In [14]:
data[names=='Bob', 3:]  

array([[2.43213425],
       [0.09362136]])

In [15]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Joe', 'Will'], dtype='<U4')

In [16]:
#'Bob'이 아닌 자료를 출력
names!='Bob'

array([False,  True,  True, False,  True,  True])

In [17]:
data[names!='Bob']

array([[ 0.03553746, -0.16168727, -1.42781337,  0.24927037],
       [ 0.34969587, -0.50383691,  1.09878003,  1.27534775],
       [-0.68733568,  0.23643794, -0.44920837, -0.28485182],
       [ 1.39218785,  0.30143936, -2.40804762, -1.65668287]])

In [22]:
~(names=='Bob')  #이것도 마찬가지로 names가 Bob이 아닌 것 참조
#비교연산 결과의 반대

array([False,  True,  True, False,  True,  True])

In [24]:
data[~(names=='Bob')]

array([[ 0.03553746, -0.16168727, -1.42781337,  0.24927037],
       [ 0.34969587, -0.50383691,  1.09878003,  1.27534775],
       [-0.68733568,  0.23643794, -0.44920837, -0.28485182],
       [ 1.39218785,  0.30143936, -2.40804762, -1.65668287]])

In [26]:
cond=names=='Bob'  #bob이 같은지 같지 않은지 불린값을 cond에 저장

In [28]:

data[~cond]   #names가 bob이 아닌 것 참조

array([[ 0.03553746, -0.16168727, -1.42781337,  0.24927037],
       [ 0.34969587, -0.50383691,  1.09878003,  1.27534775],
       [-0.68733568,  0.23643794, -0.44920837, -0.28485182],
       [ 1.39218785,  0.30143936, -2.40804762, -1.65668287]])

In [31]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Joe', 'Will'], dtype='<U4')

In [30]:
names=='Bob'
names=='Will'

array([False, False,  True, False, False,  True])

In [33]:
mask=(names=='Bob')|(names=='Will')   #bob이거나 will인 것 TRUE
data[mask]   #이름이 bob이거나 will인 사람의 데이터 추출

array([[-0.77422036,  0.65101708, -0.036529  ,  2.43213425],
       [ 0.34969587, -0.50383691,  1.09878003,  1.27534775],
       [ 0.56334927, -1.39183603,  1.01078987,  0.09362136],
       [ 1.39218785,  0.30143936, -2.40804762, -1.65668287]])

In [34]:
data

array([[-0.77422036,  0.65101708, -0.036529  ,  2.43213425],
       [ 0.03553746, -0.16168727, -1.42781337,  0.24927037],
       [ 0.34969587, -0.50383691,  1.09878003,  1.27534775],
       [ 0.56334927, -1.39183603,  1.01078987,  0.09362136],
       [-0.68733568,  0.23643794, -0.44920837, -0.28485182],
       [ 1.39218785,  0.30143936, -2.40804762, -1.65668287]])

In [35]:
data<0   #0보다 작은 값 TRUE

array([[ True, False,  True, False],
       [False,  True,  True, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [ True, False,  True,  True],
       [False, False,  True,  True]])

In [36]:
data[data<0]   #TRUE에 해당하는 data값 나옴 

array([-0.77422036, -0.036529  , -0.16168727, -1.42781337, -0.50383691,
       -1.39183603, -0.68733568, -0.44920837, -0.28485182, -2.40804762,
       -1.65668287])

In [37]:
data[data<0]=0    #음수인 것들은 모두 0으로 대입

In [38]:
data

array([[0.        , 0.65101708, 0.        , 2.43213425],
       [0.03553746, 0.        , 0.        , 0.24927037],
       [0.34969587, 0.        , 1.09878003, 1.27534775],
       [0.56334927, 0.        , 1.01078987, 0.09362136],
       [0.        , 0.23643794, 0.        , 0.        ],
       [1.39218785, 0.30143936, 0.        , 0.        ]])

### names에서 이름이 will이 아닌 사람들에 대한 
### index를 추출하여 data배열의 해당 index자료 값을 10으로 변경



In [41]:
names
data
data[names!='Will']=10

In [42]:
data

array([[10.        , 10.        , 10.        , 10.        ],
       [10.        , 10.        , 10.        , 10.        ],
       [ 0.34969587,  0.        ,  1.09878003,  1.27534775],
       [10.        , 10.        , 10.        , 10.        ],
       [10.        , 10.        , 10.        , 10.        ],
       [ 1.39218785,  0.30143936,  0.        ,  0.        ]])

In [43]:
arr=np.zeros((8,4))

In [47]:
arr[8]   #index에러 뜸

IndexError: index 8 is out of bounds for axis 0 with size 8

In [48]:
arr[0]=10

In [49]:
arr

array([[10., 10., 10., 10.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [50]:
for i in range(8):
    arr[i]=i+10

In [51]:
arr

array([[10., 10., 10., 10.],
       [11., 11., 11., 11.],
       [12., 12., 12., 12.],
       [13., 13., 13., 13.],
       [14., 14., 14., 14.],
       [15., 15., 15., 15.],
       [16., 16., 16., 16.],
       [17., 17., 17., 17.]])

In [52]:
arr[4]

array([14., 14., 14., 14.])

In [53]:
arr[[4]]   #arr[4]와 shape이 다름

array([[14., 14., 14., 14.]])

In [55]:
arr[4].shape
arr[[4]].shape

(1, 4)

In [57]:
arr[4,3]  #4행 3열의 요소 값 출력

14.0

In [59]:
#두 개 이상 행을 추출하려면 대괄호는 두개를 써야함!

arr[[4,3]]   #4행과 3행이 출력(지정한 순서대로 출력함)

array([[14., 14., 14., 14.],
       [13., 13., 13., 13.]])

In [60]:
arr[[-3]]  #뒤에서부터 3번째

array([[15., 15., 15., 15.]])

In [63]:
arr[[-3,-5]]

array([[15., 15., 15., 15.],
       [13., 13., 13., 13.]])

In [69]:
#8행 4열 array생성, 데이터는 10~41까지 저장

arr=np.arange(10,42)
arr=arr.reshape(8,4)
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [72]:
#arr에서 1,5,7,2행을 추출
arr[[1,5,7,2]]

array([[14, 15, 16, 17],
       [30, 31, 32, 33],
       [38, 39, 40, 41],
       [18, 19, 20, 21]])

In [73]:
arr[[1,5,7,2]][0]   #1,5,7,2추출한 행에서 0번 열만 추출

array([14, 15, 16, 17])

In [74]:
arr[[1,5,7,2],[0,3,1,2]]

array([14, 33, 39, 20])

In [78]:
arr[[1,5,7,2]]

array([[14, 15, 16, 17],
       [30, 31, 32, 33],
       [38, 39, 40, 41],
       [18, 19, 20, 21]])

## 원하는 순서대로 원하는 열 가져오고싶을 때

In [79]:


arr[[1,5,7,2]][:,[0,3,1,2]]     #1,5,7,2행에 대해서 0,3,1,2순서대로 참조

array([[14, 17, 15, 16],
       [30, 33, 31, 32],
       [38, 41, 39, 40],
       [18, 21, 19, 20]])

In [81]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [82]:
arr.T   #행과 열이 바뀜

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [84]:
#arr.T.T
arr.shape

(3, 5)

In [85]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## np.dot: 행렬 곱셉 (matrix multiply)

In [87]:
#3행 5열* 5행 3열=> 3행 5열

np.dot(arr,arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [91]:
arr=np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [93]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [97]:
x=np.random.randn(8)
y=np.random.randn(8)


In [98]:
x

array([ 2.16528962,  1.71635059, -0.21951215,  0.55444826,  0.17912455,
        0.25472322, -1.41197479,  1.25251844])

In [99]:
y

array([ 1.48587389, -0.49810667, -0.21852401,  0.8539466 ,  0.87598097,
        1.68877622,  0.59551404,  0.72823817])

In [101]:
#각 배열의 원소중 큰 값을 리턴함

np.maximum(x,y)

array([ 2.16528962,  1.71635059, -0.21852401,  0.8539466 ,  0.87598097,
        1.68877622,  0.59551404,  1.25251844])

In [102]:
#각 배열의 원소중 최소값을 리턴함

np.minimum(x,y)


array([ 1.48587389, -0.49810667, -0.21951215,  0.55444826,  0.17912455,
        0.25472322, -1.41197479,  0.72823817])

In [108]:
arr=np.random.randn(7)*5
arr

array([-1.36956932,  2.15382574, -0.65823336,  0.32958814, -6.55534939,
        0.48053897,  6.10769921])

### 정수부분과 실수부분 분리

In [114]:
np.modf(arr)
#(arr(),arry()) 튜플

(array([-0.36956932,  0.15382574, -0.65823336,  0.32958814, -0.55534939,
         0.48053897,  0.10769921]),
 array([-1.,  2., -0.,  0., -6.,  0.,  6.]))

In [117]:
# 정수, 실수 부분 따로 저장
remainder,whoe_part=np.modf(arr)

In [118]:
remainder

array([-0.36956932,  0.15382574, -0.65823336,  0.32958814, -0.55534939,
        0.48053897,  0.10769921])

In [119]:
whoe_part

array([-1.,  2., -0.,  0., -6.,  0.,  6.])

In [123]:
points=np.arange(-5,5,0.01)
points.shape

(1000,)

In [124]:
#두 개의 1차원 배열을 입력받아서 가능한 모든 (x,y) 짝을 만들 수 있는 2차원 배열 2개를 리턴

xs,ys=np.meshgrid(points,points)

In [125]:
xs.shape
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [126]:
ys.shape
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [127]:
z=np.sqrt(xs**2+ys**2)

In [128]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [132]:
x=np.arange(3)
x

array([0, 1, 2])

In [133]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [134]:
xx,yy = np.meshgrid(x,y)

In [135]:
xx

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [136]:
yy

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [140]:
#사각형의 영역

[list(zip(x,y))for x,y in zip(xx,yy)]  #요소끼리 연결되어서 list값으로 들어감

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [ ]:
#

In [149]:
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])

In [142]:
cond=np.array([True,False,True,True,False])

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [145]:
list(zip(xarr,yarr,cond))  #튜플로 연결되어있음

[(1.1, 2.1, True),
 (1.2, 2.2, False),
 (1.3, 2.3, False),
 (1.4, 2.4, True),
 (1.5, 2.5, False)]

### zip함수 활용! 중요!!!

In [144]:
#만약에 c값이 참이면 x를, 거짓이면 y를 취해라
[(x if c else y) for x,y,c in zip(xarr,yarr,cond)]

[1.1, 2.2, 2.3, 1.4, 2.5]

### where 함수: 조건을 만족하는 값 참조

In [146]:
cond

array([ True, False, False,  True, False, False])

In [150]:
#cond(조건)가 참이면 xarr, 거짓이면 yarr 취함
np.where(cond, xarr, yarr)  

ValueError: operands could not be broadcast together with shapes (6,) (5,) (5,) 

In [151]:
#4행 4열의 행렬을 randn 함수를 수행한 값으로 초기화하여 정의
#행렬의 요소값 중에서 1보다 크면 1을 출력, 작으면 0을 출력


In [156]:
arr=np.random.randn(4,4)
arr

array([[ 1.76070414,  0.21813537, -0.54657925, -0.18889241],
       [-0.49005358, -1.07329382,  0.07872711,  0.07469735],
       [ 1.03282436,  0.72010218,  0.42288571, -1.12070217],
       [-1.09677922, -1.18865641,  1.26882248, -1.83393508]])

In [157]:
np.where(arr>1,1,0)

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0]])

In [158]:
#4행 4열의 행렬을 randn 함수를 수행한 값으로 초기화하여 정의
#행렬의 요소값 중에서 1보다 크면 1을 출력, 작으면 원래 값을 그대로 출력

In [159]:
arr=np.random.randn(4,4)
arr
np.where(arr>1,1,arr)

array([[ 0.6036432 , -0.19469776, -0.46886142,  0.10082121],
       [ 1.        , -1.72703948, -1.21696275, -0.35657343],
       [ 1.        , -1.40964563, -0.88703191, -0.23283771],
       [-0.57456263,  1.        ,  0.2202894 , -0.67605197]])

## 수학 관련 함수

In [160]:
arr=np.random.randn(5,4)

In [161]:
arr

array([[ 0.67186635,  1.07781057,  1.28317061,  1.40074706],
       [ 1.5715664 ,  0.37743918, -0.80479329,  1.86316101],
       [ 1.19717034,  2.48079359,  0.63008375, -0.05862688],
       [ 0.12641317, -1.1279086 , -0.32803442,  1.00727928],
       [-1.01465043,  0.12563125,  0.46580842, -0.23001999]])

In [163]:
arr.mean()
#or
np.mean(arr)

0.5357453693348677

In [164]:
arr.sum()

10.714907386697353

In [166]:
#arr의 column에서 평균을 구해라
arr.mean(axis=1)

array([ 1.10839865,  0.75184333,  1.0623552 , -0.08056264, -0.16330768])

In [167]:
#arr의 row에서 평균을 구해라
arr.mean(axis=0)

array([0.51047317, 0.5867532 , 0.24924702, 0.7965081 ])

In [169]:
arr.sum(axis=1) #열 방향으로 이동해가면서 요소값의 합

array([ 4.4335946 ,  3.0073733 ,  4.2494208 , -0.32225057, -0.65323074])

In [170]:
arr.sum(axis=0)#행 방향으로 이동해가면서 요소값의 합

array([2.55236583, 2.933766  , 1.24623508, 3.98254048])

In [172]:
### 누적합: cumsum

In [176]:
arr=np.arange(1,8)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [177]:

arr.cumsum() #누적합

array([ 1,  3,  6, 10, 15, 21, 28])

In [178]:
arr.cumprod() #누적곱

array([   1,    2,    6,   24,  120,  720, 5040])

In [179]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [180]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [183]:
arr.cumsum(axis=0)  #행방향으로 이동(위->아래)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [184]:
print(arr.cumsum())   
print('='*50)
print(arr.cumsum(axis=0))   #행방향으로 이동(위->아래)

[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [185]:
print(arr.cumsum())
print('='*50)
print(arr.cumsum(axis=1))   #열방향으로 이동(좌->우)

[ 1  3  6 10 15 21 28 36 45]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [188]:
arr=np.random.randn(100)
arr

array([ 0.45758673, -1.32893373, -1.04334458, -1.44526974,  0.85403795,
       -0.51773924, -0.98878888, -0.72446848,  0.47798207, -0.62032926,
        0.7322199 , -1.20656811, -0.54937349, -0.40326801, -1.31870996,
       -0.08839489, -1.89542655, -0.93150835,  0.3711876 ,  1.59846659,
        0.99922136,  0.30482273, -1.6019306 ,  0.02130543,  0.1970968 ,
        0.24389494, -0.34460101, -0.56570721, -0.43219044,  1.05768588,
       -0.76778586, -1.14042566, -1.53425472, -0.22014237, -0.19401372,
       -0.95018321,  1.43857277,  1.35665503,  2.02342422, -0.61244592,
        0.05382152,  0.30471334,  0.48443982,  0.80708274, -0.31816979,
       -0.65645097,  1.89873597, -0.59708363,  0.38272202, -0.03519296,
       -0.06821433, -0.68565313, -0.75455114, -0.07793838, -1.39359222,
       -0.14576401,  0.28633148,  0.05784279, -0.09111368,  0.2599203 ,
        0.38432137, -1.44356438,  1.03307887,  0.14420311,  1.69004341,
       -1.26116027, -0.44478444, -0.6475858 ,  0.74911248,  0.71

In [189]:
arr.mean()

-0.070778572496497

In [191]:
arr.std()   #표준편차 

0.9229201016015727

In [199]:
#arr에서 양수의 합
#arr 최대값/최소값

[arr>0].sum()   #양수의 개수



AttributeError: 'list' object has no attribute 'sum'

In [201]:
arr[arr>0].sum() #양수의 합

33.00809704643559

In [202]:
arr.max()

2.4147770732723393

In [203]:
arr.min()

-1.895426554576816

In [204]:
arr

array([ 0.45758673, -1.32893373, -1.04334458, -1.44526974,  0.85403795,
       -0.51773924, -0.98878888, -0.72446848,  0.47798207, -0.62032926,
        0.7322199 , -1.20656811, -0.54937349, -0.40326801, -1.31870996,
       -0.08839489, -1.89542655, -0.93150835,  0.3711876 ,  1.59846659,
        0.99922136,  0.30482273, -1.6019306 ,  0.02130543,  0.1970968 ,
        0.24389494, -0.34460101, -0.56570721, -0.43219044,  1.05768588,
       -0.76778586, -1.14042566, -1.53425472, -0.22014237, -0.19401372,
       -0.95018321,  1.43857277,  1.35665503,  2.02342422, -0.61244592,
        0.05382152,  0.30471334,  0.48443982,  0.80708274, -0.31816979,
       -0.65645097,  1.89873597, -0.59708363,  0.38272202, -0.03519296,
       -0.06821433, -0.68565313, -0.75455114, -0.07793838, -1.39359222,
       -0.14576401,  0.28633148,  0.05784279, -0.09111368,  0.2599203 ,
        0.38432137, -1.44356438,  1.03307887,  0.14420311,  1.69004341,
       -1.26116027, -0.44478444, -0.6475858 ,  0.74911248,  0.71

In [208]:
#arr에서 양수는 모두 1로 음수는 모두 -1로 치환하시오

arr=np.where(arr>0,1,-1)
arr

array([ 1, -1, -1, -1,  1, -1, -1, -1,  1, -1,  1, -1, -1, -1, -1, -1, -1,
       -1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1, -1, -1, -1, -1,
       -1, -1,  1,  1,  1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1, -1, -1,
       -1, -1, -1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1, -1, -1,
        1,  1, -1,  1, -1,  1, -1, -1, -1,  1,  1, -1,  1,  1, -1, -1, -1,
        1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1, -1, -1,  1, -1])

### any(): 어느 하나로도 True가 있으면 True.

In [210]:
bools=np.array([False,False,True,False])

In [211]:
bools.any()

True

### all(): 모든 값이 True가 있으면 True가 출력

In [212]:
bools.all()

False

## 정렬 기능

In [214]:
arr=np.random.randn(6)
arr

array([-1.32261891,  0.29007556, -1.78502309, -0.1052648 , -0.68672206,
       -1.42036301])

In [215]:
arr.sort()

In [216]:
arr

array([-1.78502309, -1.42036301, -1.32261891, -0.68672206, -0.1052648 ,
        0.29007556])

In [223]:
arr=np.random.randn(5,3)
arr

array([[-1.50929809e+00, -6.97808161e-01,  3.37235053e-01],
       [ 8.30556544e-01,  4.38222512e-01, -1.67720530e+00],
       [ 1.22300148e+00,  2.05958018e+00, -1.62719488e-01],
       [ 1.57852817e-03, -5.64864575e-01, -5.63542104e-01],
       [ 7.94473600e-01, -3.10792460e-01,  3.62760050e-01]])

In [219]:
arr.sort()  #오름차순 , 열방향으로 정렬(디폴트)

In [220]:
arr

array([[ 0.48792207,  0.8054453 ,  0.85571339],
       [-1.28036367,  1.1080788 ,  1.17620971],
       [-0.96862533,  0.25700475,  0.79911328],
       [-0.84066784, -0.6667371 ,  2.03109699],
       [-2.10317534, -0.5930913 ,  1.94321872]])

In [225]:
arr.sort(axis=0)   #오름차순, 행방향 정렬

In [226]:
arr

array([[-1.50929809e+00, -6.97808161e-01, -1.67720530e+00],
       [ 1.57852817e-03, -5.64864575e-01, -5.63542104e-01],
       [ 7.94473600e-01, -3.10792460e-01, -1.62719488e-01],
       [ 8.30556544e-01,  4.38222512e-01,  3.37235053e-01],
       [ 1.22300148e+00,  2.05958018e+00,  3.62760050e-01]])

### numpy는 내림차순 기능 정의된 게 따로 없음; 오름차순 정렬 결과를 뒤에서부터 참조

In [227]:
arr=np.array([4,1,7,5,9])

In [229]:
np.sort(arr)
#or
arr.sort()

In [230]:
#내림차순 정렬
arr[::-1]

array([9, 7, 5, 4, 1])

### unique(): 유일한 값만 추출


In [231]:
names=np.array(['Bob','Joe','Will','Bob','Joe','Will'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [233]:
set(names)  #set형태로 출력


{'Bob', 'Joe', 'Will'}

In [234]:
sorted(set(names))

['Bob', 'Joe', 'Will']

### in1d() 함수

In [239]:
arr=np.array([6,0,0,3,2,5])

In [240]:
np.in1d(arr, [2,3,6])  #arr의 각 원소가 [2,3,6]의 원소에 포함되어 있는지 여부 출력

array([ True, False, False,  True,  True, False])

In [241]:
a=np.array([1,2,3])
b=np.array([10,20,30])

In [244]:
2*a+b
(a==2)&(b>10)

array([False,  True, False])

In [245]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [246]:
 len(a)  #행의 개수

3

In [249]:
len(a[0])  #열의 개수

TypeError: object of type 'numpy.int64' has no len()

In [251]:
np.shape(a)[0]  #행의 개수

3

In [253]:
np.shape(a)[1]  #열의 개수

IndexError: tuple index out of range

### 리스트: 1차원
### 리스트의 리스트:2차원
### 리스트의 리스트의 리스트: 3차원

In [257]:
d=np.arange(10,34).reshape(2,3,4)
d

array([[[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]],

       [[22, 23, 24, 25],
        [26, 27, 28, 29],
        [30, 31, 32, 33]]])

In [258]:
len(d)  #가장 바깥쪽 대괄호 안에 요소가 2개 있음

2

In [259]:
d[0]  #첫번째 행

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [260]:
d[1]

array([[22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33]])

In [261]:
len(d[0])  #3, 바깥쪽 대괄호 안에 요소가 3개있음

3

In [264]:
len(d[0][0])  #가장 안쪽 요소의 개수 

4

In [267]:
np.shape(d)[0]

2

In [268]:
d.ndim

3

In [272]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [275]:
#마지막 행의 마지막 열 출력
a[1][2]
#or
a[-1][-1]

5

In [276]:
x=np.array([1,2])
x.dtype

dtype('int64')

In [278]:
x=np.array([1,2.0])
x.dtype

dtype('float64')

In [279]:
x=np.array([1,2],dtype='f')  #dtype이라는 속성 줄 수 있다
x.dtype

dtype('float32')

In [280]:
x

array([1., 2.], dtype=float32)

#### np.inf : 무한대
#### np.nan : 정의할 수 없는 숫자

In [282]:
a=np.array([0,1,-1,0])
b=np.array([1,0,0,0])

In [283]:
a/b   #array([  0.,  inf, -inf,  nan]) 에러

<ipython-input-283-aae42d317509>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b
<ipython-input-283-aae42d317509>:1: RuntimeWarning: invalid value encountered in true_divide
  a/b


array([  0.,  inf, -inf,  nan])

In [285]:
np.log(0)  #-inf

<ipython-input-285-08bb29c3a2f2>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)  #-inf


-inf

### np.linspace() : 선형 함수

In [288]:
np.linspace(0,100,5)   #0~100까지 5개의 수를 구간으로 나누어 출력

array([  0.,  25.,  50.,  75., 100.])

In [295]:
a=np.arange(12)
a.reshape(3,4)
#or
a.reshape(3,-1)  #-1을 쓰면 알아서 계산해서 채워줌

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [297]:
a
#2*2*3 ->3차원 배열로 reshape
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [298]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [304]:
a=np.arange(0,12)

In [305]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [306]:
a=a.reshape(2,2,3)

In [307]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

#### # 다차원->1차원

In [312]:
#3차원->1차원
a.reshape(12,)
#or
a.flatten()
#or
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [313]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [318]:
x=np.arange(5).reshape(1,5)  #2차원 데이터([[]])
x.shape

(1, 5)

In [323]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

### np.newaxis: 1차원 증가할 때 사용하는 함수

In [326]:
#(5,)->(5,1)
print(x[:, np.newaxis])
print(x[:, np.newaxis].shape)

[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)


### stack(): 데이터를 위아래 or 좌우로 합칠 때

#### hstack: 행의 수가 같은 배열을 옆으로 연결(열이 증가)

In [328]:
a=np.ones((2,3))
b=np.zeros((2,2))

In [332]:
np.hstack([a,b])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [334]:
np.vstack([a,b])  #에러

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [336]:
a=np.ones((2,3))
b=np.zeros((2,3))

In [337]:
np.vstack([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [339]:
a=np.arange(6).reshape(2,3)

In [340]:
a

array([[0, 1, 2],
       [3, 4, 5]])

### tile: 동일한 배열 반복하여 연결

In [341]:
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [345]:
#위->아래 방향으로 3번, 좌->우 방향으로 2번 반복
np.tile(a,(3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [347]:
x=np.arange(5,14).reshape(3,3)

In [348]:
x

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

### 기술통계함수

In [351]:
len(x)  #데이터 건수

3

In [352]:
np.mean(x) #평균

9.0

In [353]:
np.var(x)  #분산

6.666666666666667

In [355]:
np.std(x)  #표준편차


2.581988897471611

In [357]:
np.median(x)  #중위수

9.0

In [360]:
np.percentile(x,0)  #최소값
np.percentile(x,25)  #1사분위수는 25% 백분위수와 같다
np.percentile(x,50)  #2
np.percentile(x,75)  #3
np.percentile(x,100) #4

5.0

In [361]:
np.random.seed(111)

In [362]:
np.random.rand(5)  #rand->0이상 1미만 난수

array([0.61217018, 0.16906975, 0.43605902, 0.76926247, 0.2953253 ])

#### shuffle함수: data가 random하게 섞이게 됨

In [367]:
x=np.arange(10)

In [368]:
np.random.shuffle(x)

In [369]:
x

array([1, 7, 3, 9, 4, 8, 0, 6, 5, 2])


#### np.random.choice

In [373]:
#데이터 샘플링 함수 프로토타입
#np.random.choice(배열, 크기, replace, 확률)

In [374]:
arr1=np.arange(11,20)

In [375]:
np.random.choice(arr1,5)   #replace=True 디폴트(복원추출)-->뽑힌 수가 또 뽑힐 수 있음

array([16, 19, 17, 13, 17])

In [376]:
np.random.choice(10,5)  #10은 np.arange(10)을 의미함

array([4, 3, 7, 9, 3])

In [377]:
np.random.choice(5,5) #확률이 동일함

array([1, 3, 0, 4, 1])

In [378]:
np.random.choice(5,5,p=[0.1,0.2,0,0.5,0.2])
#0이 뽑힐 확률 0.1, 1이 뽑힐 확률 0.2....

array([0, 3, 1, 4, 3])

In [380]:
np.random.randint(10)  #0~9까지 

6

In [381]:
np.random.randint(5,10) #5~9까지에 해당하는 난수가 하나 나옴

8

In [384]:
np.random.randint(5,10,3)  #3개 추출
#or
np.random.randint(5,10,size=5) #5개 추출

array([6, 9, 5, 7, 8])

In [389]:
x=np.unique([1,1,3,3,5])
x

array([1, 3, 5])

In [390]:
#count값을 리턴, 1이 2개, 3이 2개, 5가 1개
x=np.unique([1,1,3,3,5],return_counts=True)
x

(array([1, 3, 5]), array([2, 2, 1]))

In [391]:
x[0]

array([1, 3, 5])

In [392]:
x[1]

array([2, 2, 1])

In [394]:
#or
idx,cnt=np.unique([1,1,3,3,5],return_counts=True)
idx

array([1, 3, 5])

In [395]:
cnt

array([2, 2, 1])

In [397]:
#주사위를 5번 던져서 나온 수 집합=[1,1,3,3,5]
#2 0 2 0 1 0


In [399]:
np.bincount([1,1,3,3,5],minlength=7)  #0~6까지가 count범위

#bincount는 0부터 센다
#array([0, 2, 0, 2, 0, 1, 0])
#->0이 0개, 1이 2개, 2가 0개, 3이 2개, 4가 0개, 5가 1개, 6이 0개

array([0, 2, 0, 2, 0, 1, 0])

In [402]:
d
d=d[1:]

In [403]:
d

array([], shape=(0, 3, 4), dtype=int64)

In [409]:
# 퀴즈
#넘파이 난수 생성->로또 생성
np.random.randint(1,46,7)


array([39, 44, 11,  1, 19, 37, 35])

In [407]:
#or 
num =np.arange(1,46)

np.random.choice(num,7,replace=False)

array([45, 26, 18, 20,  2, 30, 32])