## 파이썬 연습문제

###  입력 받은 정수가 음수인지 양수인지 0인지 알려주세요.

In [ ]:
n=int(input())
if n >0:
    print('양수')
elif n <0:
    print('음수')
else:
    print('0')
    

### 'hello'를 지정한 횟수(0<=n<=3)만큼 출력해 보세요

In [2]:
def hello(x):
    if 0<=x<=3:
        print('hello'*x)

In [3]:
hello(3)

hellohellohello


### 0~9사이의 정수를 거꾸로 출력해보세요

In [4]:
for i in range(9,-1,-1):
    print(i)

9
8
7
6
5
4
3
2
1
0


### 임의의 리스트를 생성한 후 , 리스트를 거꾸로 출력하는 반복문을 만들어보세요

In [5]:
li=['A','B','C','D','E','F']
for i in range(len(li)-1,-1,-1):
    print(li[i])

F
E
D
C
B
A


In [6]:
for i,v in enumerate(li):
    print(i,v)

0 A
1 B
2 C
3 D
4 E
5 F


### 리스트에서 중복 값을 제거해보세요.

In [7]:
ns=[1,2,3,3,5,7,8,8]
set(ns)

{1, 2, 3, 5, 7, 8}

## Numpy 연습문제

### 1) 랜덤하게 실수로 이루어진 5*6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

In [8]:
import numpy as np

In [9]:
arr=np.random.randint(25,size=5*6).reshape(5,6)
arr

array([[ 3,  7, 14, 13, 18, 18],
       [11, 11, 18, 12, 19,  3],
       [21,  3, 10, 19,  9,  6],
       [10, 12, 11, 21, 23,  3],
       [12,  1, 11,  9,  1,  0]])

### -전체의 최댓값

In [10]:
arr.max()

23

### 각 행의 합

In [11]:
arr.sum(axis=0)

array([57, 34, 64, 74, 70, 30])

### 각 행의 최댓값

In [12]:
arr.max(axis=0)

array([21, 12, 18, 21, 23, 18])

### -각 열의 평균

In [13]:
arr.mean(axis=1)

array([12.16666667, 12.33333333, 11.33333333, 13.33333333,  5.66666667])

### 각 열의 최솟값

In [14]:
arr.min(axis=1)

array([3, 3, 3, 3, 0])

## 2)다음 행렬과 같은 행렬이 있다.

In [16]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### 이 행렬에서 값 7을 인덱싱한다

In [17]:
m[1,2]

7

#### 이 행렬에서 값 14를 인덱싱한다

In [18]:
m[2,4]

14

#### 이 행렬에서 배열 [6,7]을 슬라이싱한다

In [21]:
m[1,1:3]

array([6, 7])

#### 이 행렬에서 배열 [7,12]을 슬라이싱한다

In [22]:
m[1:,2]

array([ 7, 12])

#### 이 행렬에서 배열[[3,4],[8,9]]을 슬라이싱 한다

In [24]:
m[:2,3:]
#or
m[:2,-2:]

array([[3, 4],
       [8, 9]])

### 3) 지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라. (코드를 효율적으로)


In [25]:
"""
array([[   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.]])
       """

'\narray([[   0.,    0.,    0.,    1.,    1.],\n       [   0.,    0.,    0.,    1.,    1.],\n       [   0.,    0.,    0.,    1.,    1.],\n       [  10.,   20.,   30.,   40.,   50.],\n       [  60.,   70.,   80.,   90.,  100.],\n       [ 110.,  120.,  130.,  140.,  150.],\n       [   0.,    0.,    0.,    1.,    1.],\n       [   0.,    0.,    0.,    1.,    1.],\n       [   0.,    0.,    0.,    1.,    1.],\n       [  10.,   20.,   30.,   40.,   50.],\n       [  60.,   70.,   80.,   90.,  100.],\n       [ 110.,  120.,  130.,  140.,  150.]])\n       '

In [42]:
a1=np.hstack([np.zeros((1,3)),np.ones((1,2))])
a2=np.tile(a1,(3,1))

b=np.linspace(10,150,15).reshape(3,5)
b
np.tile(np.vstack([a2,b]),(2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

### 4)다음 행렬과 같은 배열이 있다

In [45]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### 이 배열에서 3의 배수를 찾아라

In [47]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

#### 이 배열에서 4로 나누면 1이 남는 수를 찾아차

In [48]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

#### -이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.


In [51]:
x[(x%3==0)&(x%4==1)]

array([9])

### 5) -동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.


In [53]:
for _ in range(10):
    print(np.random.randint(2))

0
1
0
0
0
0
0
1
1
1


### -주사위를 100번 던져서 나오는 숫자의 평균을 구하라.


In [54]:
dice=np.random.randint(1,7,size=100)
dice.mean()

3.2

### 6)다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.


In [66]:
arr=np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
arr

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

#### -영어 성적을 기준으로 각 열(column)을 재정렬하라

In [67]:
index = arr[1].argsort()
index

array([0, 3, 1, 2])

In [63]:
arr[:,index]

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 81,  59,  90, 100]])

### iris data 유사 데이터 추출

In [76]:
pip install -U scikit-learn scipy matplotlib

     |████████████████████████████████| 7.2 MB 953 kB/s eta 0:00:01
     |████████████████████████████████| 30.8 MB 1.0 MB/s eta 0:00:01     |███████████████████████████████▍| 30.1 MB 1.0 MB/s eta 0:00:01
     |████████████████████████████████| 8.5 MB 1.1 MB/s eta 0:00:01
     |████████████████████████████████| 61 kB 327 kB/s eta 0:00:01
     |████████████████████████████████| 2.2 MB 1.3 MB/s eta 0:00:01
     |████████████████████████████████| 303 kB 959 kB/s eta 0:00:01
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [77]:
from sklearn.datasets import load_iris



In [80]:
iris = load_iris()  # 데이터 로드


In [84]:
df=iris.data 
df[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [85]:
df[0,:]

array([5.1, 3.5, 1.4, 0.2])

In [86]:
df.shape[0]   #행 길이


150

### 첫번째 꽃 데이터와 가장 유사한 꽃 데이터를 출력

In [93]:
min_value=np.inf
index=0

In [94]:
for i in range(1,df.shape[0]):
    e_distance=(((df[0,:]-df[i,:])**2).sum())**0.5
    if e_distance < min_value:
        min_value= e_distance
        index=i

In [95]:
print('가장 유사한 꽃 index: {}, 유클리디안 거리: {}'. format(index, min_value))

가장 유사한 꽃 index: 17, 유클리디안 거리: 0.09999999999999998


In [96]:
print(df[0,:])
print(df[index,:])

[5.1 3.5 1.4 0.2]
[5.1 3.5 1.4 0.3]
