## 파이썬 연습문제

###  입력 받은 정수가 음수인지 양수인지 0인지 알려주세요.

In [ ]:
n=int(input())
if n >0:
    print('양수')
elif n <0:
    print('음수')
else:
    print('0')
    

### 'hello'를 지정한 횟수(0<=n<=3)만큼 출력해 보세요

In [7]:
def hello(x):
    if 0<=x<=3:
        print('hello'*x)

In [8]:
hello(3)

hellohellohello


### 0~9사이의 정수를 거꾸로 출력해보세요

In [15]:
for i in range(9,-1,-1):
    print(i)

9
8
7
6
5
4
3
2
1
0


### 임의의 리스트를 생성한 후 , 리스트를 거꾸로 출력하는 반복문을 만들어보세요

In [16]:
li=['A','B','C','D','E','F']
for i in range(len(li)-1,-1,-1):
    print(li[i])

F
E
D
C
B
A


In [17]:
for i,v in enumerate(li):
    print(i,v)

0 A
1 B
2 C
3 D
4 E
5 F


### 리스트에서 중복 값을 제거해보세요.

In [19]:
ns=[1,2,3,3,5,7,8,8]
set(ns)

{1, 2, 3, 5, 7, 8}

## Numpy 연습문제

### 1) 랜덤하게 실수로 이루어진 5*6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

In [20]:
import numpy as np

In [21]:
arr=np.random.randint(25,size=5*6).reshape(5,6)
arr

array([[19,  9,  1, 14, 23, 20],
       [14, 22,  5, 18, 21,  0],
       [12, 20,  6, 15, 22, 14],
       [17, 22, 17,  6, 19, 19],
       [22,  5,  2, 13,  7, 16]])

### -전체의 최댓값

In [22]:
arr.max()

23

### 각 행의 합

In [23]:
arr.sum(axis=0)

array([84, 78, 31, 66, 92, 69])

### 각 행의 최댓값

In [24]:
arr.max(axis=0)

array([22, 22, 17, 18, 23, 20])

### -각 열의 평균

In [25]:
arr.mean(axis=1)

array([14.33333333, 13.33333333, 14.83333333, 16.66666667, 10.83333333])